apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-payments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-payments
  template:
    metadata:
      labels:
        app: api-payments
    spec:
      containers:
      - name: container-api-payments
        image: viniciusdelr/payments-service:latest 
        imagePullPolicy: Always 
        ports:
        - containerPort: 80 
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: servico-api-payments
spec:
  type: LoadBalancer 
  selector:
    app: api-payments
  ports:
  - protocol: TCP
    port: 80      
    targetPort: 80 